
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IFormationService", targetNamespace = "http://service.demoFormation.ensup.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFormationService {


    /**
     * 
     * @param arg0
     * @return
     *     returns client.Formation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lireFormation", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.LireFormation")
    @ResponseWrapper(localName = "lireFormationResponse", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.LireFormationResponse")
    @Action(input = "http://service.demoFormation.ensup.eu/IFormationService/lireFormationRequest", output = "http://service.demoFormation.ensup.eu/IFormationService/lireFormationResponse")
    public Formation lireFormation(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creationFormation", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.CreationFormation")
    @ResponseWrapper(localName = "creationFormationResponse", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.CreationFormationResponse")
    @Action(input = "http://service.demoFormation.ensup.eu/IFormationService/creationFormationRequest", output = "http://service.demoFormation.ensup.eu/IFormationService/creationFormationResponse")
    public boolean creationFormation(
        @WebParam(name = "arg0", targetNamespace = "")
        Formation arg0);

    /**
     * 
     * @return
     *     returns java.util.List<client.Formation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lireTouteFormation", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.LireTouteFormation")
    @ResponseWrapper(localName = "lireTouteFormationResponse", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.LireTouteFormationResponse")
    @Action(input = "http://service.demoFormation.ensup.eu/IFormationService/lireTouteFormationRequest", output = "http://service.demoFormation.ensup.eu/IFormationService/lireTouteFormationResponse")
    public List<Formation> lireTouteFormation();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimerFormation", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.SupprimerFormation")
    @ResponseWrapper(localName = "supprimerFormationResponse", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.SupprimerFormationResponse")
    @Action(input = "http://service.demoFormation.ensup.eu/IFormationService/supprimerFormationRequest", output = "http://service.demoFormation.ensup.eu/IFormationService/supprimerFormationResponse")
    public boolean supprimerFormation(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns client.Formation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierFormation", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.ModifierFormation")
    @ResponseWrapper(localName = "modifierFormationResponse", targetNamespace = "http://service.demoFormation.ensup.eu/", className = "client.ModifierFormationResponse")
    @Action(input = "http://service.demoFormation.ensup.eu/IFormationService/modifierFormationRequest", output = "http://service.demoFormation.ensup.eu/IFormationService/modifierFormationResponse")
    public Formation modifierFormation(
        @WebParam(name = "arg0", targetNamespace = "")
        Formation arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

}
